Traceback (most recent call last):
  File "/home/linares/miniconda3/envs/echem/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/linares/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linares/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linares/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linares/miniconda3/envs/echem/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/linares/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/linares/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/linares/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import multipsi as mtp

npoints = 21
CIDrv =  mtp.CIDriver()
space = mtp.OrbSpace(mol, scf_drv.mol_orbs)
space.fci()

energies = []
for i in range(npoints):
    lambda_val = i / (npoints-1)
    CIDrv._update_integrals(mol.nuclear_repulsion_energy(), H0_1 + lambda_val* V_1, lambda_val* V_2)
    ci_results = CIDrv.compute(mol, basis, space, 1)
    energies.append(CIDrv.get_energy())
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[15], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mmultipsi[39;00m [38;5;28;01mas[39;00m [38;5;21;01mmtp[39;00m
[1;32m      3[0m npoints [38;5;241m=[39m [38;5;241m21[39m
[1;32m      4[0m CIDrv [38;5;241m=[39m  mtp[38;5;241m.[39mCIDriver()

[0;31mModuleNotFoundError[0m: No module named 'multipsi'
ModuleNotFoundError: No module named 'multipsi'

