Traceback (most recent call last):
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/client.py", line 778, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 189, in ensure_async
    result = await obj
             ^^^^^^^^^
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/site-packages/jupyter_client/channels.py", line 315, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/client.py", line 1001, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/client.py", line 802, in _async_poll_for_reply
    error_on_timeout_execute_reply = await self._async_handle_timeout(timeout, cell)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/client.py", line 852, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 120 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['mol_str = """', 'Cr 0.0 0.0 -0.825', 'Cr 0.0 0.0  0.825', ' """', '']
...
['', 'space = mtp.OrbSpace(molecule,guessorb)', 'space.cas(12,12)', 'mcscfdrv = mtp.McscfDriver()', 'mcresults = mcscfdrv.compute(molecule,basis,space)']
-------------------

