Traceback (most recent call last):
  File "/home/thomas/Notebook/anaconda/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/thomas/Notebook/anaconda/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/thomas/Notebook/anaconda/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/thomas/Notebook/anaconda/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/thomas/Notebook/anaconda/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/thomas/Notebook/anaconda/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/thomas/Notebook/anaconda/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/thomas/Notebook/anaconda/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# molecule and basis

mol_xyz = """12
c2h4-dimer
C         -1.37731        1.01769       -0.71611
C         -0.04211        1.07142       -0.72602
H         -1.96225        1.74636       -0.16458
H         -1.90859        0.23094       -1.24174
H          0.49049        1.84498       -0.18262
H          0.54315        0.32947       -1.25941
C         -1.18880       -1.26220        2.03150
C          0.05470       -0.84410        2.28420
H         -1.37000       -2.18130        1.48410
H          0.91550       -1.41310        1.94850
H         -2.04870       -0.68100        2.34880
H          0.23460        0.08670        2.81250
"""
molecule = vlx.Molecule.from_xyz_string(mol_xyz)
basis = vlx.MolecularBasis.read(molecule, 'def2-svp')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-2-4db9728688dc>[0m in [0;36m<module>[0;34m[0m
[1;32m     16[0m [0mH[0m          [0;36m0.23460[0m        [0;36m0.08670[0m        [0;36m2.81250[0m[0;34m[0m[0;34m[0m[0m
[1;32m     17[0m """
[0;32m---> 18[0;31m [0mmolecule[0m [0;34m=[0m [0mvlx[0m[0;34m.[0m[0mMolecule[0m[0;34m.[0m[0mfrom_xyz_string[0m[0;34m([0m[0mmol_xyz[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     19[0m [0mbasis[0m [0;34m=[0m [0mvlx[0m[0;34m.[0m[0mMolecularBasis[0m[0;34m.[0m[0mread[0m[0;34m([0m[0mmolecule[0m[0;34m,[0m [0;34m'def2-svp'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: type object 'veloxchem.veloxchemlib.Molecule' has no attribute 'from_xyz_string'
AttributeError: type object 'veloxchem.veloxchemlib.Molecule' has no attribute 'from_xyz_string'

