Traceback (most recent call last):
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Create the Hessian Driver and use it to compute an analytical SCF Hessian
hessian_settings = {'numerical': 'yes', 'do_four_point':'no'}
cphf_settings = {'use_subspace_solver':'yes'}
hessian_drv = vlx.scfhessiandriver.ScfHessianDriver(scfdrv, scfdrv.comm, ostream)
hessian_drv.update_settings(method_settings, hessian_settings, cphf_settings)
hessian_drv.compute(molecule, basis)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/tmp/ipykernel_11402/1749751321.py[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0mhessian_settings[0m [0;34m=[0m [0;34m{[0m[0;34m'numerical'[0m[0;34m:[0m [0;34m'yes'[0m[0;34m,[0m [0;34m'do_four_point'[0m[0;34m:[0m[0;34m'no'[0m[0;34m}[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0mcphf_settings[0m [0;34m=[0m [0;34m{[0m[0;34m'use_subspace_solver'[0m[0;34m:[0m[0;34m'yes'[0m[0;34m}[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0mhessian_drv[0m [0;34m=[0m [0mvlx[0m[0;34m.[0m[0mscfhessiandriver[0m[0;34m.[0m[0mScfHessianDriver[0m[0;34m([0m[0mscfdrv[0m[0;34m,[0m [0mscfdrv[0m[0;34m.[0m[0mcomm[0m[0;34m,[0m [0mostream[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0mhessian_drv[0m[0;34m.[0m[0mupdate_settings[0m[0;34m([0m[0mmethod_settings[0m[0;34m,[0m [0mhessian_settings[0m[0;34m,[0m [0mcphf_settings[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m [0mhessian_drv[0m[0;34m.[0m[0mcompute[0m[0;34m([0m[0mmolecule[0m[0;34m,[0m [0mbasis[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: module 'veloxchem' has no attribute 'scfhessiandriver'
AttributeError: module 'veloxchem' has no attribute 'scfhessiandriver'

