Traceback (most recent call last):
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
D = np.einsum("ik,jk->ij", C_s[:, :nocc], C_s[:, :nocc])
mu_s = dipmom(D)

D = np.einsum("ik,jk->ij", C_d[:, :nocc], C_d[:, :nocc])
mu_d = dipmom(D)

D = np.einsum("ik,jk->ij", C_a[:, :nocc], C_a[:, :nocc])
mu_a = dipmom(D)

print(f"   vacuum: {np.linalg.norm(mu_HF) : 8.6f}")
print(f" solution: {np.linalg.norm(mu_s) : 8.6f}")
print(f"   donors: {np.linalg.norm(mu_d) : 8.6f}")
print(f"acceptors: {np.linalg.norm(mu_a) : 8.6f}")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn [15], line 2[0m
[1;32m      1[0m D [38;5;241m=[39m np[38;5;241m.[39meinsum([38;5;124m"[39m[38;5;124mik,jk->ij[39m[38;5;124m"[39m, C_s[:, :nocc], C_s[:, :nocc])
[0;32m----> 2[0m mu_s [38;5;241m=[39m [43mdipmom[49m[43m([49m[43mD[49m[43m)[49m
[1;32m      4[0m D [38;5;241m=[39m np[38;5;241m.[39meinsum([38;5;124m"[39m[38;5;124mik,jk->ij[39m[38;5;124m"[39m, C_d[:, :nocc], C_d[:, :nocc])
[1;32m      5[0m mu_d [38;5;241m=[39m dipmom(D)

[0;31mTypeError[0m: dipmom() missing 1 required positional argument: 'molecule'
TypeError: dipmom() missing 1 required positional argument: 'molecule'

