Traceback (most recent call last):
  File "/home/thomas/Notebook/anaconda/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/thomas/Notebook/anaconda/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/thomas/Notebook/anaconda/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/thomas/Notebook/anaconda/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/thomas/Notebook/anaconda/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/thomas/Notebook/anaconda/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/thomas/Notebook/anaconda/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/thomas/Notebook/anaconda/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# mo values at given coordinates
mol_orbs = scf_drv.mol_orbs

n = 100
coords = np.zeros((n,3))
coords[:,2] = np.linspace(-3, 3, n, endpoint=True)

sigma_g = np.array(vis_drv.get_mo(coords, molecule, basis, mol_orbs, 0, 'alpha'))
sigma_u = np.array(vis_drv.get_mo(coords, molecule, basis, mol_orbs, 1, 'alpha'))

n1_HF = 2 * sigma_g**2
n1_CID = 2 * (c_HF**2 * sigma_g**2 + c_uu**2 * sigma_u**2)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-9-e4b5a466d8c1>[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0mcoords[0m[0;34m[[0m[0;34m:[0m[0;34m,[0m[0;36m2[0m[0;34m][0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mlinspace[0m[0;34m([0m[0;34m-[0m[0;36m3[0m[0;34m,[0m [0;36m3[0m[0;34m,[0m [0mn[0m[0;34m,[0m [0mendpoint[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0;34m[0m[0m
[0;32m----> 8[0;31m [0msigma_g[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0marray[0m[0;34m([0m[0mvis_drv[0m[0;34m.[0m[0mget_mo[0m[0;34m([0m[0mcoords[0m[0;34m,[0m [0mmolecule[0m[0;34m,[0m [0mbasis[0m[0;34m,[0m [0mmol_orbs[0m[0;34m,[0m [0;36m0[0m[0;34m,[0m [0;34m'alpha'[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      9[0m [0msigma_u[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0marray[0m[0;34m([0m[0mvis_drv[0m[0;34m.[0m[0mget_mo[0m[0;34m([0m[0mcoords[0m[0;34m,[0m [0mmolecule[0m[0;34m,[0m [0mbasis[0m[0;34m,[0m [0mmol_orbs[0m[0;34m,[0m [0;36m1[0m[0;34m,[0m [0;34m'alpha'[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     10[0m [0;34m[0m[0m

[0;31mAttributeError[0m: 'veloxchem.veloxchemlib.VisualizationDriver' object has no attribute 'get_mo'
AttributeError: 'veloxchem.veloxchemlib.VisualizationDriver' object has no attribute 'get_mo'

