Traceback (most recent call last):
  File "/home/thomas/Notebook/anaconda/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/thomas/Notebook/anaconda/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/thomas/Notebook/anaconda/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/thomas/Notebook/anaconda/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/thomas/Notebook/anaconda/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/thomas/Notebook/anaconda/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/thomas/Notebook/anaconda/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/thomas/Notebook/anaconda/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import py3Dmol
import numpy as np
import matplotlib.pyplot as plt
import veloxchem as vlx
from pyscf import gto, scf, tools
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
[0;32m~/Notebook/anaconda/lib/python3.7/site-packages/pyscf/lib/misc.py[0m in [0;36mload_library[0;34m(libname)[0m
[1;32m     53[0m         [0m_loaderpath[0m [0;34m=[0m [0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0mdirname[0m[0;34m([0m[0m__file__[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 54[0;31m         [0;32mreturn[0m [0mnumpy[0m[0;34m.[0m[0mctypeslib[0m[0;34m.[0m[0mload_library[0m[0;34m([0m[0mlibname[0m[0;34m,[0m [0m_loaderpath[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     55[0m     [0;32mexcept[0m [0mOSError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Notebook/anaconda/lib/python3.7/site-packages/numpy/ctypeslib.py[0m in [0;36mload_library[0;34m(libname, loader_path)[0m
[1;32m    149[0m                 [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 150[0;31m                     [0;32mreturn[0m [0mctypes[0m[0;34m.[0m[0mcdll[0m[0;34m[[0m[0mlibpath[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    151[0m                 [0;32mexcept[0m [0mOSError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Notebook/anaconda/lib/python3.7/ctypes/__init__.py[0m in [0;36m__getitem__[0;34m(self, name)[0m
[1;32m    438[0m     [0;32mdef[0m [0m__getitem__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mname[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 439[0;31m         [0;32mreturn[0m [0mgetattr[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    440[0m [0;34m[0m[0m

[0;32m~/Notebook/anaconda/lib/python3.7/ctypes/__init__.py[0m in [0;36m__getattr__[0;34m(self, name)[0m
[1;32m    433[0m             [0;32mraise[0m [0mAttributeError[0m[0;34m([0m[0mname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 434[0;31m         [0mdll[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_dlltype[0m[0;34m([0m[0mname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    435[0m         [0msetattr[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mname[0m[0;34m,[0m [0mdll[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Notebook/anaconda/lib/python3.7/ctypes/__init__.py[0m in [0;36m__init__[0;34m(self, name, mode, handle, use_errno, use_last_error)[0m
[1;32m    363[0m         [0;32mif[0m [0mhandle[0m [0;32mis[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 364[0;31m             [0mself[0m[0;34m.[0m[0m_handle[0m [0;34m=[0m [0m_dlopen[0m[0;34m([0m[0mself[0m[0;34m.[0m[0m_name[0m[0;34m,[0m [0mmode[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    365[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mOSError[0m: libmkl_intel_lp64.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

[0;31mOSError[0m                                   Traceback (most recent call last)
[0;32m<ipython-input-1-f4a64f26f042>[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0;32mimport[0m [0mmatplotlib[0m[0;34m.[0m[0mpyplot[0m [0;32mas[0m [0mplt[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;32mimport[0m [0mveloxchem[0m [0;32mas[0m [0mvlx[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m [0;32mfrom[0m [0mpyscf[0m [0;32mimport[0m [0mgto[0m[0;34m,[0m [0mscf[0m[0;34m,[0m [0mtools[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/Notebook/anaconda/lib/python3.7/site-packages/pyscf/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m    111[0m [0;34m[0m[0m
[1;32m    112[0m [0;32mfrom[0m [0mpyscf[0m [0;32mimport[0m [0m__config__[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 113[0;31m [0;32mfrom[0m [0mpyscf[0m [0;32mimport[0m [0mlib[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    114[0m [0;32mfrom[0m [0mpyscf[0m [0;32mimport[0m [0mgto[0m[0;34m[0m[0;34m[0m[0m
[1;32m    115[0m [0;32mfrom[0m [0mpyscf[0m [0;32mimport[0m [0mscf[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Notebook/anaconda/lib/python3.7/site-packages/pyscf/lib/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m     22[0m [0;32mfrom[0m [0mpyscf[0m[0;34m.[0m[0mlib[0m [0;32mimport[0m [0mparameters[0m[0;34m[0m[0;34m[0m[0m
[1;32m     23[0m [0mparam[0m [0;34m=[0m [0mparameters[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 24[0;31m [0;32mfrom[0m [0mpyscf[0m[0;34m.[0m[0mlib[0m [0;32mimport[0m [0mnumpy_helper[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     25[0m [0;32mfrom[0m [0mpyscf[0m[0;34m.[0m[0mlib[0m [0;32mimport[0m [0mlinalg_helper[0m[0;34m[0m[0;34m[0m[0m
[1;32m     26[0m [0;32mfrom[0m [0mpyscf[0m[0;34m.[0m[0mlib[0m [0;32mimport[0m [0mscipy_helper[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Notebook/anaconda/lib/python3.7/site-packages/pyscf/lib/numpy_helper.py[0m in [0;36m<module>[0;34m[0m
[1;32m     37[0m     [0mFOUND_TBLIS[0m [0;34m=[0m [0;32mFalse[0m[0;34m[0m[0;34m[0m[0m
[1;32m     38[0m [0;34m[0m[0m
[0;32m---> 39[0;31m [0m_np_helper[0m [0;34m=[0m [0mmisc[0m[0;34m.[0m[0mload_library[0m[0;34m([0m[0;34m'libnp_helper'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     40[0m [0;34m[0m[0m
[1;32m     41[0m [0mBLOCK_DIM[0m [0;34m=[0m [0;36m192[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Notebook/anaconda/lib/python3.7/site-packages/pyscf/lib/misc.py[0m in [0;36mload_library[0;34m(libname)[0m
[1;32m     60[0m                 [0;32mfor[0m [0mfiles[0m [0;32min[0m [0mos[0m[0;34m.[0m[0mlistdir[0m[0;34m([0m[0mlibpath[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     61[0m                     [0;32mif[0m [0mfiles[0m[0;34m.[0m[0mstartswith[0m[0;34m([0m[0mlibname[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 62[0;31m                         [0;32mreturn[0m [0mnumpy[0m[0;34m.[0m[0mctypeslib[0m[0;34m.[0m[0mload_library[0m[0;34m([0m[0mlibname[0m[0;34m,[0m [0mlibpath[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     63[0m         [0;32mraise[0m[0;34m[0m[0;34m[0m[0m
[1;32m     64[0m [0;34m[0m[0m

[0;32m~/Notebook/anaconda/lib/python3.7/site-packages/numpy/ctypeslib.py[0m in [0;36mload_library[0;34m(libname, loader_path)[0m
[1;32m    148[0m             [0;32mif[0m [0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0mexists[0m[0;34m([0m[0mlibpath[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    149[0m                 [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 150[0;31m                     [0;32mreturn[0m [0mctypes[0m[0;34m.[0m[0mcdll[0m[0;34m[[0m[0mlibpath[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    151[0m                 [0;32mexcept[0m [0mOSError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    152[0m                     [0;31m## defective lib file[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Notebook/anaconda/lib/python3.7/ctypes/__init__.py[0m in [0;36m__getitem__[0;34m(self, name)[0m
[1;32m    437[0m [0;34m[0m[0m
[1;32m    438[0m     [0;32mdef[0m [0m__getitem__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mname[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 439[0;31m         [0;32mreturn[0m [0mgetattr[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    440[0m [0;34m[0m[0m
[1;32m    441[0m     [0;32mdef[0m [0mLoadLibrary[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mname[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Notebook/anaconda/lib/python3.7/ctypes/__init__.py[0m in [0;36m__getattr__[0;34m(self, name)[0m
[1;32m    432[0m         [0;32mif[0m [0mname[0m[0;34m[[0m[0;36m0[0m[0;34m][0m [0;34m==[0m [0;34m'_'[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    433[0m             [0;32mraise[0m [0mAttributeError[0m[0;34m([0m[0mname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 434[0;31m         [0mdll[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_dlltype[0m[0;34m([0m[0mname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    435[0m         [0msetattr[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mname[0m[0;34m,[0m [0mdll[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    436[0m         [0;32mreturn[0m [0mdll[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Notebook/anaconda/lib/python3.7/ctypes/__init__.py[0m in [0;36m__init__[0;34m(self, name, mode, handle, use_errno, use_last_error)[0m
[1;32m    362[0m [0;34m[0m[0m
[1;32m    363[0m         [0;32mif[0m [0mhandle[0m [0;32mis[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 364[0;31m             [0mself[0m[0;34m.[0m[0m_handle[0m [0;34m=[0m [0m_dlopen[0m[0;34m([0m[0mself[0m[0;34m.[0m[0m_name[0m[0;34m,[0m [0mmode[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    365[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    366[0m             [0mself[0m[0;34m.[0m[0m_handle[0m [0;34m=[0m [0mhandle[0m[0;34m[0m[0;34m[0m[0m

[0;31mOSError[0m: libmkl_intel_lp64.so.1: cannot open shared object file: No such file or directory
OSError: libmkl_intel_lp64.so.1: cannot open shared object file: No such file or directory

