Traceback (most recent call last):
  File "/home/thomas/Notebook/anaconda/envs/echem_test/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/thomas/Notebook/anaconda/envs/echem_test/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/thomas/Notebook/anaconda/envs/echem_test/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/thomas/Notebook/anaconda/envs/echem_test/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/thomas/Notebook/anaconda/envs/echem_test/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/thomas/Notebook/anaconda/envs/echem_test/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/thomas/Notebook/anaconda/envs/echem_test/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/thomas/Notebook/anaconda/envs/echem_test/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
display(caffeine_noH, useSVG=True)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 1[0m
[0;32m----> 1[0m [43mdisplay[49m[43m([49m[43mcaffeine_noH[49m[43m,[49m[43m [49m[43museSVG[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m

File [0;32m~/Notebook/anaconda/envs/echem_test/lib/python3.9/site-packages/IPython/core/display_functions.py:305[0m, in [0;36mdisplay[0;34m(include, exclude, metadata, transient, display_id, raw, clear, *objs, **kwargs)[0m
[1;32m    302[0m         [38;5;28;01mif[39;00m metadata:
[1;32m    303[0m             [38;5;66;03m# kwarg-specified metadata gets precedence[39;00m
[1;32m    304[0m             _merge(md_dict, metadata)
[0;32m--> 305[0m         [43mpublish_display_data[49m[43m([49m[43mdata[49m[38;5;241;43m=[39;49m[43mformat_dict[49m[43m,[49m[43m [49m[43mmetadata[49m[38;5;241;43m=[39;49m[43mmd_dict[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    306[0m [38;5;28;01mif[39;00m display_id:
[1;32m    307[0m     [38;5;28;01mreturn[39;00m DisplayHandle(display_id)

File [0;32m~/Notebook/anaconda/envs/echem_test/lib/python3.9/site-packages/IPython/core/display_functions.py:93[0m, in [0;36mpublish_display_data[0;34m(data, metadata, source, transient, **kwargs)[0m
[1;32m     90[0m [38;5;28;01mif[39;00m transient:
[1;32m     91[0m     kwargs[[38;5;124m'[39m[38;5;124mtransient[39m[38;5;124m'[39m] [38;5;241m=[39m transient
[0;32m---> 93[0m [43mdisplay_pub[49m[38;5;241;43m.[39;49m[43mpublish[49m[43m([49m
[1;32m     94[0m [43m    [49m[43mdata[49m[38;5;241;43m=[39;49m[43mdata[49m[43m,[49m
[1;32m     95[0m [43m    [49m[43mmetadata[49m[38;5;241;43m=[39;49m[43mmetadata[49m[43m,[49m
[1;32m     96[0m [43m    [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m
[1;32m     97[0m [43m[49m[43m)[49m

[0;31mTypeError[0m: publish() got an unexpected keyword argument 'useSVG'
TypeError: publish() got an unexpected keyword argument 'useSVG'

